env:
  es2020: true
  node: true
  mocha: true
extends:
  - standard
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
